import test from 'node:test';
import assert from 'node:assert/strict';

import { createBootstrapController } from '../js/app/bootstrap-controller.js';

test('bootstrapPostCore exposes post-core bootstrap stage for command/auth wiring', async () => {
  const controller = createBootstrapController({
    state: { sets: [], quickFilters: {}, allSets: [], summaryData: [], currentSet: null },
    dom: {
      auth: { dataset: { state: 'in' }, disabled: false, addEventListener: () => {} },
      load: { addEventListener: () => {} },
      refresh: { addEventListener: () => {} },
      selector: { value: '', addEventListener: () => {} },
      btnMissingExport: { addEventListener: () => {} },
      navSetSplit: { contains: () => false, classList: { contains: () => false } },
      refreshSplit: { contains: () => false },
      refreshMenu: { classList: { contains: () => true } },
      btnRefreshMenu: { disabled: true, addEventListener: () => {} },
      btnRefreshReimport: { addEventListener: () => {} },
      btnNavSetToggle: { disabled: true, addEventListener: () => {} },
      search: { focus: () => {} },
    },
    config: { SPREADSHEET_ID: 'sheet-1' },
    eventBus: { on: () => {} },
    eventQuickFiltersChanged: 'quick-filters-changed',
    eventClearSearchHistory: 'clear-search-history',
    loadDashboardPreferences: () => {},
    loadRecentSets: () => [],
    initSmartEngine: async () => {},
    runCardmarketVersioningCheck: async () => ({ changed: false, reason: 'first-sync', previousStamp: '', currentStamp: '', reset: [] }),
    initAutoHideTopbar: () => {},
    initGridZoom: () => {},
    initCustomSelects: () => {},
    initFilterButtons: () => {},
    spreadsheetDialogController: { initSpreadsheetDialog: () => {} },
    initBatchImportDialog: () => {},
    initManageImportedSetsDialog: () => {},
    initBackupImportExport: () => {},
    initQueueBuilderDialog: () => {},
    initSetViewController: () => {},
    createSetViewInjections: () => ({}),
    createDashboardRenderer: () => ({}),
    createStatsRenderer: () => ({}),
    createSettingsController: () => ({}),
    createStatsPriceViewController: () => ({}),
    dashboardRendererDeps: {},
    statsRendererDeps: {},
    settingsControllerDeps: {},
    assignDashboardRenderer: () => {},
    assignStatsRenderer: () => {},
    assignSettingsController: () => {},
    initDashboardControls: () => {},
    initSheetsWriteFeedback: () => {},
    initAuditAndSaveUi: () => {},
    initDevCompletionMode: () => {},
    initSortControl: () => {},
    initSearch: () => {},
    initOfflineIndicator: () => {},
    initDashboardHoverPreview: () => {},
    initSearchAutocomplete: () => {},
    initShareButton: () => {},
    initRealtimeSync: () => ({}),
    realtimeClientStorageKey: 'realtime-client-id',
    applyIncomingRealtimeUpdate: () => {},
    initQuickFiltersUI: () => {},
    resetDashboardVirtualization: () => {},
    saveDashboardPreferences: () => {},
    renderDashboard: () => {},
    loadSearchHistory: () => [],
    clearSearchHistory: () => {},
    showToast: () => {},
    openBatchImportDialog: () => {},
    runDataHealthCheck: () => {},
    downloadJson: () => {},
    runPokecodeParityTest: async () => {},
    loadSnapshots: () => [],
    openSettingsDialog: () => {},
    generateCollectionReport: () => ({}),
    createExportDialog: () => ({ showModal: () => {}, addEventListener: () => {}, remove: () => {} }),
    createWishlistPanel: () => ({}),
    createSharingDialog: () => ({}),
    createTradingLogPanel: () => ({}),
    calculateCollectionStats: () => ({}),
    createAchievementsPanel: () => ({}),
    createCSVExportPanel: () => ({}),
    createLocalBackup: () => null,
    getLocalBackups: () => [],
    createCommunityStatsBanner: () => ({}),
    createCommunityTrendingPanel: () => ({}),
    createCommunitySearchPanel: () => ({}),
    createPublicShare: () => null,
    getTrendingCollections: () => [],
    createSharedCollectionCard: () => ({}),
    createTradeStatsCard: () => ({}),
    createTradeMarketplacePanel: () => ({}),
    createTradeSuggestionsPanel: () => ({}),
    createWantedCardsPanel: () => ({}),
    getAvailableRarities: () => [],
    getCollectionValueStats: () => ({ totalValue: 0, cardCount: 0, averageValue: 0 }),
    getTradePlaceSummary: () => ({}),
    userIdStorageKey: 'user-id',
    getUserProfile: () => null,
    createUserProfile: () => ({ userId: 'u1' }),
    createUserProfileCard: () => ({}),
    initCommandPalette: () => {},
    getEngineMetrics: () => ({ cacheHitRate: 0, status: 'offline', syncQueue: [] }),
    navigate: () => {},
    setRecentSetsDropdownOpen: () => {},
    setRefreshMenuOpen: () => {},
    positionRecentSetsDropdown: () => {},
    handleRouteChange: () => {},
    setLoading: () => {},
    setGlobalStatus: () => {},
    initAuth: async () => false,
    syncAuthButtonLabel: () => {},
    signIn: async () => false,
    signOut: () => {},
    resetToLoggedOut: () => {},
    isSignedIn: () => false,
    loadCurrentSet: async () => {},
    reimportCurrentSetFromApi: async () => {},
    exportMissingCards: () => {},
    onLoginSuccess: () => {},
    showView: () => {},
    syncRefreshControls: () => {},
    syncSetNavLink: () => {},
    setEmptyState: () => {},
    documentRef: {
      body: { appendChild: () => {} },
      createElement: () => ({
        className: '',
        style: { cssText: '' },
        appendChild: () => {},
        addEventListener: () => {},
        showModal: () => {},
        remove: () => {},
        close: () => {},
        innerHTML: '',
        textContent: '',
      }),
      getElementById: () => null,
      querySelectorAll: () => [],
      addEventListener: () => {},
    },
    windowRef: {
      addEventListener: () => {},
      setTimeout: (fn) => fn(),
      location: { reload: () => {} },
    },
    localStorageRef: {
      getItem: () => null,
      setItem: () => {},
    },
  });

  assert.equal(typeof controller.bootstrapPostCore, 'function');
});
